# { "Depends": "py-genlayer:1jb45aa8ynh2a9c9xn3b7qqh8sm5q93hwfp7jqmwsfhh8jpz09h6" }

from genlayer import *

import hashlib
from datetime import datetime, timezone


@gl.evm.contract_interface
class _Recipient:
    class View:
        pass

    class Write:
        pass


class ProllyV2(gl.Contract):
    """
    Prolly V2.

    GenLayer is the source of truth.

    Architecture:

        OPEN
          ↓
        USERS JOIN
          ↓
        MAX PARTICIPANTS REACHED
          ↓
        AUTOMATIC CLOSE
          ↓
        PARTICIPANTS FROZEN
          ↓
        FINALIZATION
          ↓
        DETERMINISTIC WINNER CALCULATION
          ↓
        WINNERS STORED IMMUTABLY
          ↓
        FRONTEND BATTLE MODE
          ↓
        WINNERS REVEALED
          ↓
        WINNER CLAIMS PRIZE

    IMPORTANT:

    - Admin cannot select winners.
    - Sponsor cannot select winners.
    - Users cannot select winners.
    - AI cannot select lottery winners.
    - Frontend cannot select winners.
    - Battle Mode cannot select winners.
    - Winner records cannot be changed after finalization.

    Winner calculation happens entirely from immutable on-chain
    participant state plus the finalized selection seed.

    The frontend is presentation only.
    """

    # ===============================================================
    # CONSTANTS
    # ===============================================================

    PLATFORM_FEE_BPS: u256 = u256(500)
    BPS_DENOMINATOR: u256 = u256(10_000)

    # ===============================================================
    # GLOBAL STATE
    # ===============================================================

    owner: Address
    next_prolly_id: u256

    total_platform_fees: u256
    total_platform_fees_withdrawn: u256

    # Total prize money currently reserved for all Prollys.
    #
    # This protects winner funds from platform-fee withdrawals.
    total_reserved_prizes: u256

    # ===============================================================
    # PROLLY STATE
    # ===============================================================

    names: TreeMap[u256, str]

    entry_fees: TreeMap[u256, u256]
    max_participants: TreeMap[u256, u256]
    winner_counts: TreeMap[u256, u256]

    participant_counts: TreeMap[u256, u256]

    # Entry fees only.
    prize_pools: TreeMap[u256, u256]

    # Total prize amount already claimed.
    claimed_prizes: TreeMap[u256, u256]

    closed: TreeMap[u256, bool]
    winner_finalized: TreeMap[u256, bool]

    # ===============================================================
    # PLATFORM FEES
    # ===============================================================

    # Total platform fees generated by this Prolly.
    platform_fee_balances: TreeMap[u256, u256]

    # ===============================================================
    # PARTICIPANTS
    # ===============================================================

    # "prolly_id:address" -> true
    participants: TreeMap[str, bool]

    # "prolly_id:index" -> address
    participant_by_index: TreeMap[str, str]

    # "prolly_id:address" -> index
    participant_order: TreeMap[str, u256]

    # ===============================================================
    # WINNERS
    # ===============================================================

    # "prolly_id:winner_index" -> address
    winners: TreeMap[str, str]

    # "prolly_id:winner_index" -> prize
    winner_prizes: TreeMap[str, u256]

    # "prolly_id:winner_index" -> claimed
    winner_claimed: TreeMap[str, bool]

    # ===============================================================
    # RANDOMNESS / FINALIZATION
    # ===============================================================

    # Final deterministic selection seed.
    randomness_seeds: TreeMap[u256, str]

    # Finalization transaction timestamp.
    finalized_at: TreeMap[u256, u256]

    # ===============================================================
    # CONSTRUCTOR
    # ===============================================================

    def __init__(self):
        self.owner = gl.message.sender_address
        self.next_prolly_id = u256(1)

        self.total_platform_fees = u256(0)
        self.total_platform_fees_withdrawn = u256(0)

        self.total_reserved_prizes = u256(0)

    # ===============================================================
    # INTERNAL HELPERS
    # ===============================================================

    def _require_owner(self) -> None:
        if self.owner != gl.message.sender_address:
            raise gl.vm.UserError(
                "Only owner can perform this action"
            )

    def _require_exists(
        self,
        prolly_id: u256,
    ) -> None:
        if prolly_id not in self.names:
            raise gl.vm.UserError(
                "Prolly does not exist"
            )

    def _participant_key(
        self,
        prolly_id: u256,
        participant: str,
    ) -> str:
        return f"{prolly_id}:{participant}"

    def _index_key(
        self,
        prolly_id: u256,
        index: u256,
    ) -> str:
        return f"{prolly_id}:{index}"

    def _winner_key(
        self,
        prolly_id: u256,
        winner_index: u256,
    ) -> str:
        return f"{prolly_id}:{winner_index}"

    def _platform_fee(
        self,
        entry_fee: u256,
    ) -> u256:
        return (
            entry_fee
            * self.PLATFORM_FEE_BPS
        ) // self.BPS_DENOMINATOR

    # ===============================================================
    # DETERMINISTIC SELECTION SEED
    # ===============================================================

    def _build_selection_seed(
        self,
        prolly_id: u256,
        participant_count: u256,
    ) -> str:
        """
        Build the deterministic selection seed.

        The seed commits to:

        - contract address
        - Prolly ID
        - final participant count
        - finalization transaction timestamp

        GenLayer pins transaction time consistently across validators.

        IMPORTANT:

        This is a deterministic seed construction, not a claim that
        transaction time itself is a cryptographic randomness beacon.

        The purpose of this function is to make the final winner
        calculation reproducible and auditable.
        """

        timestamp = datetime.now(
            timezone.utc
        ).isoformat()

        raw = (
            "PROLLY-V2-SELECTION|"
            f"{gl.message.contract_address}|"
            f"{prolly_id}|"
            f"{participant_count}|"
            f"{timestamp}"
        )

        return hashlib.sha256(
            raw.encode()
        ).hexdigest()

    def _seed_number(
        self,
        seed: str,
        offset: u256,
    ) -> u256:
        """
        Expand the final seed into deterministic numbers.
        """

        raw = (
            f"PROLLY-V2-DRAW|"
            f"{seed}|"
            f"{offset}"
        ).encode()

        digest = hashlib.sha256(
            raw
        ).hexdigest()

        return u256(
            int(digest, 16)
        )

    # ===============================================================
    # CREATE PROLLY
    # ===============================================================

    @gl.public.write
    def create_prolly(
        self,
        name: str,
        entry_fee: u256,
        max_participants: u256,
        winner_count: u256,
    ) -> u256:

        self._require_owner()

        if len(name.strip()) == 0:
            raise gl.vm.UserError(
                "Prolly name is required"
            )

        if entry_fee <= 0:
            raise gl.vm.UserError(
                "Entry fee must be greater than zero"
            )

        if max_participants <= 0:
            raise gl.vm.UserError(
                "Maximum participants must be greater than zero"
            )

        if winner_count <= 0:
            raise gl.vm.UserError(
                "Winner count must be greater than zero"
            )

        if winner_count > max_participants:
            raise gl.vm.UserError(
                "Winner count cannot exceed maximum participants"
            )

        prolly_id = self.next_prolly_id

        self.next_prolly_id = (
            prolly_id + 1
        )

        self.names[prolly_id] = (
            name.strip()
        )

        self.entry_fees[prolly_id] = (
            entry_fee
        )

        self.max_participants[prolly_id] = (
            max_participants
        )

        self.winner_counts[prolly_id] = (
            winner_count
        )

        self.participant_counts[prolly_id] = (
            u256(0)
        )

        self.prize_pools[prolly_id] = (
            u256(0)
        )

        self.claimed_prizes[prolly_id] = (
            u256(0)
        )

        self.platform_fee_balances[prolly_id] = (
            u256(0)
        )

        self.closed[prolly_id] = False

        self.winner_finalized[prolly_id] = (
            False
        )

        self.randomness_seeds[prolly_id] = ""

        self.finalized_at[prolly_id] = (
            u256(0)
        )

        return prolly_id

    # ===============================================================
    # JOIN PROLLY
    # ===============================================================

    @gl.public.write.payable
    def join(
        self,
        prolly_id: u256,
    ) -> None:

        self._require_exists(
            prolly_id
        )

        if self.closed.get(
            prolly_id,
            False,
        ):
            raise gl.vm.UserError(
                "Prolly is closed"
            )

        participant = str(
            gl.message.sender_address
        )

        participant_key = (
            self._participant_key(
                prolly_id,
                participant,
            )
        )

        if participant_key in self.participants:
            raise gl.vm.UserError(
                "Wallet already joined this Prolly"
            )

        count = self.participant_counts.get(
            prolly_id,
            u256(0),
        )

        limit = self.max_participants[
            prolly_id
        ]

        if count >= limit:
            raise gl.vm.UserError(
                "Prolly is full"
            )

        entry_fee = self.entry_fees[
            prolly_id
        ]

        platform_fee = self._platform_fee(
            entry_fee
        )

        if platform_fee == 0:
            raise gl.vm.UserError(
                "Entry fee is too small for platform fee"
            )

        required_payment = (
            entry_fee + platform_fee
        )

        if gl.message.value != required_payment:
            raise gl.vm.UserError(
                "Incorrect payment amount"
            )

        # -----------------------------------------------------------
        # RECORD PARTICIPANT
        # -----------------------------------------------------------

        self.participants[
            participant_key
        ] = True

        index_key = self._index_key(
            prolly_id,
            count,
        )

        self.participant_by_index[
            index_key
        ] = participant

        self.participant_order[
            participant_key
        ] = count

        self.participant_counts[
            prolly_id
        ] = count + 1

        # -----------------------------------------------------------
        # PRIZE POOL
        # -----------------------------------------------------------

        current_pool = (
            self.prize_pools.get(
                prolly_id,
                u256(0),
            )
        )

        self.prize_pools[
            prolly_id
        ] = (
            current_pool + entry_fee
        )

        # -----------------------------------------------------------
        # PLATFORM FEE
        # -----------------------------------------------------------

        current_fee = (
            self.platform_fee_balances.get(
                prolly_id,
                u256(0),
            )
        )

        self.platform_fee_balances[
            prolly_id
        ] = (
            current_fee + platform_fee
        )

        self.total_platform_fees = (
            self.total_platform_fees
            + platform_fee
        )

        # -----------------------------------------------------------
        # AUTOMATIC CLOSE
        # -----------------------------------------------------------

        if count + 1 >= limit:
            self.closed[
                prolly_id
            ] = True

    # ===============================================================
    # CLOSE PROLLY
    # ===============================================================

    @gl.public.write
    def close_prolly(
        self,
        prolly_id: u256,
    ) -> None:

        self._require_owner()

        self._require_exists(
            prolly_id
        )

        if self.closed.get(
            prolly_id,
            False,
        ):
            return

        self.closed[
            prolly_id
        ] = True

    # ===============================================================
    # FINALIZE WINNERS
    # ===============================================================

    @gl.public.write
    def finalize_winners(
        self,
        prolly_id: u256,
    ) -> None:

        self._require_exists(
            prolly_id
        )

        # -----------------------------------------------------------
        # IMPORTANT:
        #
        # Finalization is PERMISSIONLESS.
        #
        # Admin does not choose when the transaction is authorized
        # by access control.
        #
        # Once the Prolly is closed, anyone may trigger finalization.
        # -----------------------------------------------------------

        if not self.closed.get(
            prolly_id,
            False,
        ):
            raise gl.vm.UserError(
                "Prolly is not closed"
            )

        if self.winner_finalized.get(
            prolly_id,
            False,
        ):
            raise gl.vm.UserError(
                "Winners already finalized"
            )

        participant_count = (
            self.participant_counts.get(
                prolly_id,
                u256(0),
            )
        )

        if participant_count == 0:
            raise gl.vm.UserError(
                "Cannot finalize a Prolly with no participants"
            )

        winner_count = self.winner_counts[
            prolly_id
        ]

        if winner_count > participant_count:
            raise gl.vm.UserError(
                "Winner count exceeds participant count"
            )

        prize_pool = (
            self.prize_pools.get(
                prolly_id,
                u256(0),
            )
        )

        if prize_pool == 0:
            raise gl.vm.UserError(
                "Prize pool is empty"
            )

        # -----------------------------------------------------------
        # PARTICIPANTS ARE NOW FROZEN
        #
        # `closed == True` prevents further joins.
        #
        # Therefore the participant list used by this calculation
        # cannot change after this point.
        # -----------------------------------------------------------

        # -----------------------------------------------------------
        # FINALIZATION TIMESTAMP
        # -----------------------------------------------------------

        finalization_timestamp = u256(
            int(
                datetime.now(
                    timezone.utc
                ).timestamp()
            )
        )

        self.finalized_at[
            prolly_id
        ] = finalization_timestamp

        # -----------------------------------------------------------
        # BUILD FINAL SEED
        # -----------------------------------------------------------

        seed = self._build_selection_seed(
            prolly_id,
            participant_count,
        )

        self.randomness_seeds[
            prolly_id
        ] = seed

        # -----------------------------------------------------------
        # SELECT UNIQUE WINNERS
        # -----------------------------------------------------------

        selected = u256(0)
        offset = u256(0)

        while selected < winner_count:

            random_number = (
                self._seed_number(
                    seed,
                    offset,
                )
            )

            candidate_index = (
                random_number
                % participant_count
            )

            candidate_key = (
                self._index_key(
                    prolly_id,
                    candidate_index,
                )
            )

            candidate = (
                self.participant_by_index[
                    candidate_key
                ]
            )

            already_selected = False

            check_index = u256(0)

            while check_index < selected:

                previous_winner_key = (
                    self._winner_key(
                        prolly_id,
                        check_index,
                    )
                )

                if (
                    self.winners.get(
                        previous_winner_key,
                        "",
                    )
                    == candidate
                ):
                    already_selected = True
                    break

                check_index = (
                    check_index + 1
                )

            if not already_selected:

                winner_key = (
                    self._winner_key(
                        prolly_id,
                        selected,
                    )
                )

                self.winners[
                    winner_key
                ] = candidate

                selected = (
                    selected + 1
                )

            offset = (
                offset + 1
            )

        # -----------------------------------------------------------
        # DISTRIBUTE PRIZES
        # -----------------------------------------------------------

        base_prize = (
            prize_pool
            // winner_count
        )

        remainder = (
            prize_pool
            % winner_count
        )

        prize_index = u256(0)

        while prize_index < winner_count:

            winner_key = (
                self._winner_key(
                    prolly_id,
                    prize_index,
                )
            )

            prize = base_prize

            if prize_index < remainder:
                prize = prize + 1

            self.winner_prizes[
                winner_key
            ] = prize

            self.winner_claimed[
                winner_key
            ] = False

            prize_index = (
                prize_index + 1
            )

        # -----------------------------------------------------------
        # RESERVE THE ENTIRE PRIZE POOL
        # -----------------------------------------------------------

        self.total_reserved_prizes = (
            self.total_reserved_prizes
            + prize_pool
        )

        # -----------------------------------------------------------
        # FINALIZATION IS NOW IMMUTABLE
        # -----------------------------------------------------------

        self.winner_finalized[
            prolly_id
        ] = True

    # ===============================================================
    # CLAIM WINNER PRIZE
    # ===============================================================

    @gl.public.write
    def claim_winner(
        self,
        prolly_id: u256,
        winner_index: u256,
    ) -> None:

        self._require_exists(
            prolly_id
        )

        if not self.winner_finalized.get(
            prolly_id,
            False,
        ):
            raise gl.vm.UserError(
                "Winners are not finalized"
            )

        winner_count = self.winner_counts[
            prolly_id
        ]

        if winner_index >= winner_count:
            raise gl.vm.UserError(
                "Invalid winner index"
            )

        winner_key = (
            self._winner_key(
                prolly_id,
                winner_index,
            )
        )

        winner = self.winners.get(
            winner_key,
            "",
        )

        if winner == "":
            raise gl.vm.UserError(
                "Winner does not exist"
            )

        caller = str(
            gl.message.sender_address
        )

        if caller != winner:
            raise gl.vm.UserError(
                "Only the selected winner can claim"
            )

        if self.winner_claimed.get(
            winner_key,
            False,
        ):
            raise gl.vm.UserError(
                "Prize already claimed"
            )

        prize = self.winner_prizes.get(
            winner_key,
            u256(0),
        )

        if prize == 0:
            raise gl.vm.UserError(
                "Winner prize is zero"
            )

        claimed = self.claimed_prizes.get(
            prolly_id,
            u256(0),
        )

        prize_pool = self.prize_pools.get(
            prolly_id,
            u256(0),
        )

        if claimed + prize > prize_pool:
            raise gl.vm.UserError(
                "Prize pool accounting error"
            )

        if self.balance < prize:
            raise gl.vm.UserError(
                "Contract balance is insufficient for prize"
            )

        # -----------------------------------------------------------
        # MARK CLAIM BEFORE TRANSFER
        # -----------------------------------------------------------

        self.winner_claimed[
            winner_key
        ] = True

        self.claimed_prizes[
            prolly_id
        ] = claimed + prize

        # -----------------------------------------------------------
        # RELEASE RESERVED PRIZE FUNDS
        # -----------------------------------------------------------

        self.total_reserved_prizes = (
            self.total_reserved_prizes
            - prize
        )

        # -----------------------------------------------------------
        # TRANSFER
        # -----------------------------------------------------------

        _Recipient(
            Address(winner)
        ).emit_transfer(
            value=prize
        )

    # ===============================================================
    # WITHDRAW PLATFORM FEES
    # ===============================================================

    @gl.public.write
    def withdraw_platform_fees(
        self,
        amount: u256,
    ) -> None:

        self._require_owner()

        if amount <= 0:
            raise gl.vm.UserError(
                "Withdrawal amount must be greater than zero"
            )

        available_fees = (
            self.total_platform_fees
            - self.total_platform_fees_withdrawn
        )

        if amount > available_fees:
            raise gl.vm.UserError(
                "Insufficient platform fee balance"
            )

        # -----------------------------------------------------------
        # NEVER SPEND FUNDS RESERVED FOR WINNERS
        # -----------------------------------------------------------

        if self.balance < (
            self.total_reserved_prizes
            + amount
        ):
            raise gl.vm.UserError(
                "Withdrawal would reduce reserved prize funds"
            )

        self.total_platform_fees_withdrawn = (
            self.total_platform_fees_withdrawn
            + amount
        )

        _Recipient(
            self.owner
        ).emit_transfer(
            value=amount
        )

    # ===============================================================
    # READ — GLOBAL
    # ===============================================================

    @gl.public.view
    def get_owner(self) -> Address:
        return self.owner

    @gl.public.view
    def get_next_prolly_id(self) -> u256:
        return self.next_prolly_id

    @gl.public.view
    def get_total_platform_fees(self) -> u256:
        return self.total_platform_fees

    @gl.public.view
    def get_total_platform_fees_withdrawn(
        self,
    ) -> u256:
        return self.total_platform_fees_withdrawn

    @gl.public.view
    def get_available_platform_fees(
        self,
    ) -> u256:
        return (
            self.total_platform_fees
            - self.total_platform_fees_withdrawn
        )

    @gl.public.view
    def get_total_reserved_prizes(
        self,
    ) -> u256:
        return self.total_reserved_prizes

    @gl.public.view
    def get_contract_balance(self) -> u256:
        return self.balance

    # ===============================================================
    # READ — PROLLY
    # ===============================================================

    @gl.public.view
    def get_name(
        self,
        prolly_id: u256,
    ) -> str:
        return self.names.get(
            prolly_id,
            "",
        )

    @gl.public.view
    def get_entry_fee(
        self,
        prolly_id: u256,
    ) -> u256:
        return self.entry_fees.get(
            prolly_id,
            u256(0),
        )

    @gl.public.view
    def get_platform_fee(
        self,
        prolly_id: u256,
    ) -> u256:
        return self._platform_fee(
            self.entry_fees.get(
                prolly_id,
                u256(0),
            )
        )

    @gl.public.view
    def get_platform_fee_balance(
        self,
        prolly_id: u256,
    ) -> u256:
        return self.platform_fee_balances.get(
            prolly_id,
            u256(0),
        )

    @gl.public.view
    def get_available_platform_fee(
        self,
        prolly_id: u256,
    ) -> u256:
        return self.platform_fee_balances.get(
            prolly_id,
            u256(0),
        )

    @gl.public.view
    def get_max_participants(
        self,
        prolly_id: u256,
    ) -> u256:
        return self.max_participants.get(
            prolly_id,
            u256(0),
        )

    @gl.public.view
    def get_winner_count(
        self,
        prolly_id: u256,
    ) -> u256:
        return self.winner_counts.get(
            prolly_id,
            u256(0),
        )

    @gl.public.view
    def get_participant_count(
        self,
        prolly_id: u256,
    ) -> u256:
        return self.participant_counts.get(
            prolly_id,
            u256(0),
        )

    @gl.public.view
    def get_prize_pool(
        self,
        prolly_id: u256,
    ) -> u256:
        return self.prize_pools.get(
            prolly_id,
            u256(0),
        )

    @gl.public.view
    def get_claimed_prizes(
        self,
        prolly_id: u256,
    ) -> u256:
        return self.claimed_prizes.get(
            prolly_id,
            u256(0),
        )

    @gl.public.view
    def get_remaining_prizes(
        self,
        prolly_id: u256,
    ) -> u256:

        pool = self.prize_pools.get(
            prolly_id,
            u256(0),
        )

        claimed = self.claimed_prizes.get(
            prolly_id,
            u256(0),
        )

        return pool - claimed

    @gl.public.view
    def is_closed(
        self,
        prolly_id: u256,
    ) -> bool:
        return self.closed.get(
            prolly_id,
            False,
        )

    @gl.public.view
    def are_winners_finalized(
        self,
        prolly_id: u256,
    ) -> bool:
        return self.winner_finalized.get(
            prolly_id,
            False,
        )

    # ===============================================================
    # READ — PARTICIPANTS
    # ===============================================================

    @gl.public.view
    def has_joined(
        self,
        prolly_id: u256,
        participant: str,
    ) -> bool:

        return self.participants.get(
            self._participant_key(
                prolly_id,
                participant,
            ),
            False,
        )

    @gl.public.view
    def get_participant(
        self,
        prolly_id: u256,
        index: u256,
    ) -> str:

        return self.participant_by_index.get(
            self._index_key(
                prolly_id,
                index,
            ),
            "",
        )

    @gl.public.view
    def get_participant_index(
        self,
        prolly_id: u256,
        participant: str,
    ) -> u256:

        return self.participant_order.get(
            self._participant_key(
                prolly_id,
                participant,
            ),
            u256(0),
        )

    # ===============================================================
    # READ — WINNERS
    # ===============================================================

    @gl.public.view
    def get_winner(
        self,
        prolly_id: u256,
        index: u256,
    ) -> str:

        return self.winners.get(
            self._winner_key(
                prolly_id,
                index,
            ),
            "",
        )

    @gl.public.view
    def get_winner_prize(
        self,
        prolly_id: u256,
        index: u256,
    ) -> u256:

        return self.winner_prizes.get(
            self._winner_key(
                prolly_id,
                index,
            ),
            u256(0),
        )

    @gl.public.view
    def is_winner_claimed(
        self,
        prolly_id: u256,
        index: u256,
    ) -> bool:

        return self.winner_claimed.get(
            self._winner_key(
                prolly_id,
                index,
            ),
            False,
        )

    # ===============================================================
    # READ — RANDOMNESS / FINALIZATION
    # ===============================================================

    @gl.public.view
    def get_randomness_seed(
        self,
        prolly_id: u256,
    ) -> str:

        return self.randomness_seeds.get(
            prolly_id,
            "",
        )

    @gl.public.view
    def get_finalized_at(
        self,
        prolly_id: u256,
    ) -> u256:

        return self.finalized_at.get(
            prolly_id,
            u256(0),
        )
